### ISSUE TITLE
skins enabled

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1373]

**Comment by Plushtoast** [comment]
Developers which want to create their own style should basically do this:
* Create a new module
* Add scoped CSS styles
* Add JS file and register the style via the hook "registerDSAstyle"

Example:
```scss
//(s)css style file
.dsa5-myStyleName {
    p{ 
        color: darkblue; 
    }
    ...all my style code
}
```

```js
Hooks.on("registerDSAstyle", styles => {
    styles["dsa5-myStyleName"] = "Some fancy style name which can also be translated with lang files";
})
```
